#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=4gb
#PBS -l walltime=00:30:00
#PBS -N detect-ecg-artifacts

set -e
set -x

time singularity exec -e docker://brainlife/mne:0.19.2 ./detect.py

#create product.json
cat << EOF > product.json
{
    "brainlife": [
        { 
            "type": "image/png", 
            "name": "Number of detected ECG artifacts",
            "base64": "$(base64 -w 0 ecg_artifacts.png)"
        }
    ]
}
EOF
